@echo off
echo Starting Prime Tech AI Voice Agent Backend...
echo.
echo Step 1: Installing dependencies...
pip install -r requirements.txt
echo.
echo Step 2: Starting server...
uvicorn app.main:app --host 0.0.0.0 --port 8030 --reload
